/*
Goals: 
0. I want users writing a schema to be guided by types
1. I want to define the schema as minimally and ergonomically as possible.
2. I want migration functions up and down to provide static and/or runtime type support based on the prev/next schema definitions
3. I want return types from query() for a given store, and insert/update parameter types to be infered from the schema
4. If user has to write a typescript type next to their schema that's fine but less ideal.

Approach:
1. Write a custom schema type next to your schema
2. extend some base shared goldfish types (that include things like private, ids, etc.)
3. once working and wired up, see what can be infered from the schema definition directly


*/

// NOTE: adding :SchemaDefinition here overrites this specific type generated by all the schemaUtil functions
const mySchema = schema({
  // version of your schema, for user defined versioned migrations of user data
  v: 1,
  // test: 'broken',
  // TODO: a collection can be anywhere in the data structure but it can't be nested
  // eg: config.thing.somecollection: collection({})
  stores: {
    // test: "broken",
    user: collection({
      // test: 'broken',
      username: string({ required: true }),
      // date_created: timestamp(),
      email: string({ required: true }),
      pass: string(),
      emailConfirmed: boolean(),
      loginCount: number(),
      skills: array(
        object({
          name: string(),
          ability: string(),
          rating: number(),
        })
      ),
      // // TODO: need an enum type, although maybe we use string + allowed values?
      betaFlags: array(string()),
      preferences: object({
        darkMode: boolean(),
        largeText: boolean(),
      }),
      // // This is the first schema definition for the user collection so no migration needed
    }),
    config: keyValue(
      {
        api_key_service1: string(),
        // api_key_service2: string(),
      },
      { migrations: false }
    ),
    // needed for migrating top-level properties
  },
});

type UserSchemaType = typeof mySchema.stores.user.schema;
type UserDocType = StoreSchemaToDocumentType<UserSchemaType>;

// NOTE: this is better than above because if schema.stores is not of the shape SchemaDefinition this will error
// but it doesn't type check top level shape of schema
type SchemaDocumentTypes = SchemaToDocumentTypes<typeof mySchema>;

const userDoc: SchemaDocumentTypes["user"] = {
  username: "yoav",
  email: "yoav@chalk.sh",
  pass: "922929",
  loginCount: 5,
  emailConfirmed: false,
  skills: [
    {
      name: "flight",
      ability: "to fly",
      rating: 5,
    },
  ],
  betaFlags: [
    "flag1",
    "flag2", // 5
  ],
  preferences: {
    darkMode: true,
    largeText: false,
    // test: 'broken',
  },
};

type ConfigSchemaType = typeof mySchema.stores.config.schema;
type ConfigDocType = StoreSchemaToDocumentType<ConfigSchemaType>;

const configDoc: SchemaDocumentTypes["config"] = {
  api_key_service1: "29230jfa09sdfj",
  // test: 'broken',
};

// const schemaObj = {
//   v: 1,
//   stores: {
//     // test: 'broken',
//     user: {
//       type: "collection",
//       migrations: false,
//       schema: {
//         username: {
//           type: "string",
//           required: true,
//         },
//         email: {
//           type: "string",
//           required: true,
//         },
//         pass: {
//           type: "string",
//         },
//         loginCount: {
//           type: "number",
//         },
//         emailConfirmed: {
//           type: "boolean"
//         },
//         skills: {
//           type: "array",
//           schema: {
//             type: "object",
//             schema: {
//               name: {
//                 type: "string",
//               },
//               ability: {
//                 type: "string",
//               },
//               rating: {
//                 type: "number",
//               },
//             },
//           },
//         },
//         betaFlags: {
//           type: "array",
//           schema: {
//             type: "string",
//           },
//         },
//       },
//     },
//     config: {
//       type: "keyvalue",
//       migrations: false,
//       schema: {
//         api_key_service1: {
//           type: "string",
//         },
//       },
//     },
//   },
// };

// THIS WORKS:
// const testEmailString = string();
// type TestEmailProp = typeof testEmailString extends {type: 'string'} ? string : never;

// console.log(testEmailString, testEmailString)
// ////////////////
// // THIS ALSO WORKS FOR EXTRACTING TYPES
// const testUserObj = {
//   email: string(),
//   loginAttempts: number(),
//   emailConfirmed: boolean(),
// }

// type TestUserDoc = StoreSchemaToDocumentType<typeof testUserObj>
// const x: TestUserDoc = {
//   email: 'hi',
//   loginAttempts: 4,
//   emailConfirmed: false,
// }

// console.log(testUserObj, testUserObj)
// ///////////////////////
// // the problem is that collectionFactory returns a NestedSchemaType
// const testUserCollection = collection({
//   email: string(),
//   loginAttempts: number(),
//   emailConfirmed: boolean(),
// })
// type TestUserCollectionDoc = StoreSchemaToDocumentType<typeof testUserCollection['schema']>
// const y: TestUserCollectionDoc = {
//   email: 'hi',
//   loginAttempts: 4,
//   emailConfirmed: false,
// }

// const userSchemaObj = schema.stores.user.schema;
// // type ObjSchemaType = typeof userSchemaObj

// // type EmailType = SchemaObjectType.

// type UserDocObjType = StoreSchemaToDocumentType<typeof userSchemaObj>
// const objUserDoc:UserDocObjType = {
//   username: 'yoav',
//   email: 'yoav@chalk.sh',
//   pass: '922929',
//   loginCount: 5,
//   emailConfirmed: false,
//   // test: 'broken',
//   // skills: [{
//   //   name: 'flight',
//   //   ability: 'to fly',
//   //   rating: 5
//   // }],
//   // betaFlags: ['flag1', 'flag2']
// }
// console.log(userSchemaObj)
// // const testcollection: ReturnType<collection({one: string(), two: number()});

// const userSchema = schema.stores.user.schema;
// type EmailDocumentPropertyType = StoreSchemaToDocumentType<UserSchemaType>
